apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 1 # number of pods to run
  selector:
    matchLabels:
      # all pods with this label will be part of this deployment
      app: webapp
  template: # configures the pod
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: nanajanashia/k8s-demo-app:v1.0
        ports:
        - containerPort: 3000
        env:
        # pass the mongo credentials and url to the webapp container for connecting to the db
        - name: USER_NAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-user
        - name: USER_PWD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-password 
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: mongo-url

---

apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  # exposes the service on each node's IP at a static port (nodePort)
  # if type is not specified, it defaults to ClusterIP (internal service)
  type: NodePort
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      # <nodeIp:nodePort> to access the service from outside the cluster
      # ip range: 30000-32767
      nodePort: 30100 